### ISSUE TITLE
Most profiles are not found

### ISSUE THREAD

**Issue by MarkasAis** [nacho-cs/ranked-browser#1]
Profile page doesn't show when clicking on a profile link

## Reproduce:

1. Click on any name in homepage / match history
![afbeelding](https://github.com/nacho-cs/ranked-browser/assets/39225800/b6eeeaed-7b4e-4dd2-8e57-c8cdc146150a)
2. Get redirected to player page: https://ranked-browser.vercel.app/player/giannimoccolo
3. Get `404 NOT FOUND`
![afbeelding](https://github.com/nacho-cs/ranked-browser/assets/39225800/ef2c3117-e123-4980-8812-9a3553c6774f)

**Comment by nacho-cs** [comment]
Fixed. I just needed to add the `vercel.json` file.
