### ISSUE TITLE
Profile search doesn't work

### ISSUE THREAD

**Issue by MarkasAis** [nacho-cs/ranked-browser#2]
Profile search shows the wrong person most of the time. From testing, search worked for "lowk3y_" but not for any other username I tried.

## Reproduce:
1. Search a player name
![afbeelding](https://github.com/nacho-cs/ranked-browser/assets/39225800/e893bf74-e3c7-4b0e-8b1d-dcd7b0372fe2)

2. Another player's profile is shown
![afbeelding](https://github.com/nacho-cs/ranked-browser/assets/39225800/df9365a2-17d4-483e-85d6-ddfb865d02ed)

**Comment by leeoniya** [comment]
some fuzzy libs are better than others ;)

https://github.com/leeoniya/uFuzzy

**Comment by nacho-cs** [comment]
This should be fixed with the latest commit: https://github.com/nacho-cs/ranked-browser/commit/3392a8633f783750adbfc3876f273c41f6abb354. All players can now be searched, but if you want to compare players, you can do so in a separate input. This also reduced the bundle size.
